/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2df",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        secondary: "#0056c6",
        "on-secondary": "#ffffff",
        "secondary-container": "#226eed",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#d9e2ff",
        "secondary-fixed-dim": "#b0c6ff",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1c1b1a",
        "on-tertiary-container": "#868382",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "on-secondary-fixed": "#001945",
        "on-secondary-fixed-variant": "#00429b",
        "tertiary-fixed": "#e6e2df",
        "tertiary-fixed-dim": "#cac6c4",
        "on-tertiary-fixed": "#1c1b1a",
        "on-tertiary-fixed-variant": "#484645",
        background: "#faf9f6",
        "on-background": "#1b1c1a",
        "surface-variant": "#e3e2df",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        "container-margin": "32px",
        gutter: "16px",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": [
          "11px",
          { lineHeight: "1", letterSpacing: "0.03em", fontWeight: "600" },
        ],
        h1: ["42px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["22px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "h1-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": [
          "13px",
          { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" },
        ],
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
